# Uncomment these two lines to add support for right encoder
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Enable the Bluetooth BAS (battery reporting service)
CONFIG_BT_BAS=y
CONFIG_ZMK_BATTERY_REPORTING=y
